version: '3.8'

services:
  db:
    container_name: wordpress_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: unless-stopped
    volumes:
      - /home/lazaros/docker/wordpress/mysql:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8081:80
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    restart: unless-stopped
    volumes:
      - /home/lazaros/docker/wordpress/html:/var/www/html
    networks:
      - network
    depends_on:
      - db

networks:
  network:
    driver: bridge